### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Webx123** [Tinychat/Tinychat-Bot#1]
How can i make just the youtube and sound cloud for MODS only but keep the other public commands there?

**Comment by Ruddernation-Designs** [comment]
I will update a little later today to have it set to only mods. :)

**Comment by Webx123** [comment]
i love the flip and roll commands first bot to have it since the good ole days!

**Comment by Ruddernation-Designs** [comment]
Cool, Well I'm updating it now so it should be ready in a couple of hours

**Comment by Ruddernation-Designs** [comment]
I've now updated, you can download it all again or just copy and past tinybot.py file, The commands have also been updated.

**Comment by Webx123** [comment]
Can you also fix !clear please it dont do anything :(
