### ISSUE TITLE
Clear command

### ISSUE THREAD

**Issue by Webx123** [Tinychat/Tinychat-Bot#2]
Can you also fix !clear please it dont do anything :(

**Comment by Webx123** [comment]
anyway i can turn this off just for my room? like in the coding?

**Comment by Webx123** [comment]
i dont like pm commands

**Comment by Ruddernation-Designs** [comment]
You can disable it by removing the command in tinybot.py https://github.com/Tinychat/Tinychat-Bot/blob/master/tinybot.py#L1581 
Also I've done the PM commands for security purposes, most don't want the public users trying the commands themselves

**Comment by Webx123** [comment]
ohh i dont want to remove clear i want it to be a public command for everyone to use in main chat But atm it wont work in main or pm and im a mod. is there a part of the code i can edit in my tinybot.py to make it a public command?

**Comment by Ruddernation-Designs** [comment]
Yeah sure, add 
`elif cmd == prefix + 'clear':
                    self.do_clear()`
create a new line at https://github.com/Tinychat/Tinychat-Bot/blob/master/tinybot.py#L349 and then start the bot again and the !clear will work in public chat

**Comment by Ruddernation-Designs** [comment]
I've added it to a Gist, just copy and paste to tinybot.py
[https://gist.github.com/Ruddernation-Designs/554c4956be28009bf182d6714f917295](url)
