### ISSUE TITLE
not able to login with the bot

### ISSUE THREAD

**Issue by freshie2006** [Tinychat/Tinychat-Bot#2]
Hi I need LIL help I reset my bot after tc did a update changing the login page which I changed the url on the web request but it still fail to login

url was changed from /login to /start?#login

**Comment by Ruddernation-Designs** [comment]
Hello,
Thanks for informing me, I will have a look into this at some point,
I'm rather busy at the moment so I've no time frame on a fix.
Thanks

**Comment by freshie2006** [comment]
thank you for your response hopefully you will sort it out I don't understand things on how to program things yet just getting to know how things work with the bot. if you can let me know when you sort things out it will be a great help. thank you. the bot has been a great help with my room.

**Comment by ItzEvan** [comment]
Also once you get login to work commands wont work.

**Comment by Ruddernation-Designs** [comment]
I've now got this working on my new bot, So I will update this old bot later today.

**Comment by ItzEvan** [comment]
I have been trying to get a working bot all day. How will I know when its updated.

**Comment by ItzEvan** [comment]
You know if you do fix it you will be the first person with the fix especially if you have an updated repository

**Comment by Ruddernation-Designs** [comment]
I've updated the bot to the new one, This is rushed so it'll be updated again in the next couple of weeks, If you have any issues then please let me know,
I've not fully tested it yet so I expect some bugs
