### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Webx123** [Tinychat/Tinychat-Bot#3]
How would i find the Array Id of a room?

**Comment by Ruddernation-Designs** [comment]
would you want it in a command?
Basically the same as how the user spy works.

**Comment by Webx123** [comment]
yeah would be nice i just need to know how i can get the array id of a room some how haha

**Comment by Ruddernation-Designs** [comment]
Okay, something like this?
https://gist.github.com/Ruddernation-Designs/c42a641ca1d48c6c8e3551f634c6963a

**Comment by Ruddernation-Designs** [comment]
I've added it to my version of the bot, Try and let me know or is it something totally different you want?
