### ISSUE TITLE
Could you tell me how?

### ISSUE THREAD

**Issue by ItzEvan** [Tinychat/Tinychat-Bot#4]
To make it so every so often like every 10 mins the bot is up you can set it to send a message.

Something like.

Remember to Bookmark the room.

**Comment by Ruddernation-Designs** [comment]
That was removed in version 6 but I'll think about adding it in another version, you should also think about changing the greeting for now but it all depends on how many users come in and go out of your room.

**Comment by ItzEvan** [comment]
Ok yeah that is a good idea you are awesome man.

**Comment by donnyosmondfan** [comment]
how can i get bot to work through windows 8.1

**Comment by Ruddernation-Designs** [comment]
Hi Donny,
Could you tell me what errors are accruing and what version o Python you are using?

**Comment by donnyosmondfan** [comment]
I am using 27.3 version one of my friends told me to use and soon as I put
python in it just says defined

**Comment by Ruddernation-Designs** [comment]
Okay, Did you add C:\Python27 and C:\Python27\Scripts to your Environment Variables in your Advanced system settings on Windows?

**Comment by donnyosmondfan** [comment]
I ll try that but don't know what part I need to put it in though

**Comment by Ruddernation-Designs** [comment]
Click the link below and follow that, If you still can't get it to work then let me know.
https://github.com/Tinychat/Tinychat-Bot#to-be-able-to-run-pip-inside-command-prompt-on-windows-use-the-below-info

**Comment by donnyosmondfan** [comment]
I will thank you

**Comment by donnyosmondfan** [comment]
Which one do I need to click on next?

**Comment by donnyosmondfan** [comment]
Still not working

**Comment by donnyosmondfan** [comment]
Tried everything and it is not working

**Comment by Ruddernation-Designs** [comment]
Could you provide screenshots of what you're doing,
Also if you could right click the bot.py file and click run in IDLE and the press F5 for it to run and see what errors it outputs, From there we can fix it :)

**Comment by Ruddernation-Designs** [comment]
I'm sorry I'm a little slow responding but I'm cooking dinner as well lol
