### ISSUE TITLE
Have you seen this to add yt

### ISSUE THREAD

**Issue by ItzEvan** [Tinychat/Tinychat-Bot#5]
http://pastebin.com/6Pyp9p7g

**Comment by Ruddernation-Designs** [comment]
Cool Evan, 
I will look through it later and add it to the next version if it works. 👍

**Comment by ItzEvan** [comment]
Ok that would be awesome.

**Comment by ItzEvan** [comment]
Also your download counter like for the git isn't working so don't think people aren't downloading ha.

**Comment by Ruddernation-Designs** [comment]
Yeah I noticed that, I just read up on the GitHub blog and they've depreciated it and newer repositories wont show a count, Damn them! lol

**Comment by ItzEvan** [comment]
can you Check your skype I have a project for you honeslty as in I need a website built.
